/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanel.opleiding.Home;

import jpanel.opleiding.Auth.Login;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;
import jpanel.opleiding.MyConnection;

/**
 *
 * @author singh
 */
public class Home_JFrame extends javax.swing.JFrame {

    private String[] info;

    public void setInfo(String[] info) {
        this.info = info;
    }

    /**
     * Creates new form Home_JFrame
     */
    public Home_JFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelOpleiding = new javax.swing.JPanel();
        btn_AllOpleidingen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_opleiding = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btn_Survey = new javax.swing.JButton();
        btn_Verwwijder = new javax.swing.JButton();
        Profile_Panel = new javax.swing.JPanel();
        txt_username = new javax.swing.JLabel();
        txt_username1 = new javax.swing.JLabel();
        txt_username2 = new javax.swing.JLabel();
        txt_username3 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_Name = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        txt_user = new javax.swing.JTextField();
        txt_role = new javax.swing.JTextField();
        txt_username4 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        txt_username5 = new javax.swing.JLabel();
        txt_gender = new javax.swing.JTextField();
        txt_geboorteDatum = new javax.swing.JTextField();
        txt_username6 = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        btn_Profile = new javax.swing.JButton();
        btn_Opleiding = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        PanelOpleiding.setLayout(null);

        btn_AllOpleidingen.setText("All Opleidingen");
        btn_AllOpleidingen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AllOpleidingenActionPerformed(evt);
            }
        });
        PanelOpleiding.add(btn_AllOpleidingen);
        btn_AllOpleidingen.setBounds(20, 380, 300, 30);

        jScrollPane1.setViewportView(list_opleiding);

        PanelOpleiding.add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 300, 330);

        jLabel1.setText("Mijn Opleidingen");
        PanelOpleiding.add(jLabel1);
        jLabel1.setBounds(20, 20, 160, 13);

        btn_Survey.setText("Take Survey ");
        PanelOpleiding.add(btn_Survey);
        btn_Survey.setBounds(360, 90, 180, 30);

        btn_Verwwijder.setText("Verwijder deze opleiding");
        btn_Verwwijder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerwwijderActionPerformed(evt);
            }
        });
        PanelOpleiding.add(btn_Verwwijder);
        btn_Verwwijder.setBounds(360, 40, 180, 30);

        getContentPane().add(PanelOpleiding);
        PanelOpleiding.setBounds(230, 0, 580, 460);

        Profile_Panel.setLayout(null);

        txt_username.setText("email");
        Profile_Panel.add(txt_username);
        txt_username.setBounds(100, 230, 60, 20);

        txt_username1.setText("Name");
        Profile_Panel.add(txt_username1);
        txt_username1.setBounds(100, 30, 60, 20);

        txt_username2.setText("Firstname");
        Profile_Panel.add(txt_username2);
        txt_username2.setBounds(100, 70, 160, 20);

        txt_username3.setText("Username");
        Profile_Panel.add(txt_username3);
        txt_username3.setBounds(100, 190, 80, 20);
        Profile_Panel.add(txt_email);
        txt_email.setBounds(200, 230, 230, 30);
        Profile_Panel.add(txt_Name);
        txt_Name.setBounds(200, 30, 230, 30);
        Profile_Panel.add(txt_firstname);
        txt_firstname.setBounds(200, 70, 230, 30);
        Profile_Panel.add(txt_user);
        txt_user.setBounds(200, 190, 230, 30);
        Profile_Panel.add(txt_role);
        txt_role.setBounds(200, 270, 230, 30);

        txt_username4.setText("role");
        Profile_Panel.add(txt_username4);
        txt_username4.setBounds(100, 270, 60, 20);

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        Profile_Panel.add(btn_save);
        btn_save.setBounds(250, 340, 114, 30);

        txt_username5.setText("Gender");
        Profile_Panel.add(txt_username5);
        txt_username5.setBounds(100, 110, 160, 20);
        Profile_Panel.add(txt_gender);
        txt_gender.setBounds(200, 110, 230, 30);
        Profile_Panel.add(txt_geboorteDatum);
        txt_geboorteDatum.setBounds(200, 150, 230, 30);

        txt_username6.setText("Geboorte Datum");
        Profile_Panel.add(txt_username6);
        txt_username6.setBounds(100, 150, 200, 20);

        getContentPane().add(Profile_Panel);
        Profile_Panel.setBounds(230, 0, 580, 460);

        sidePanel.setBackground(new java.awt.Color(0, 102, 204));

        btn_Profile.setBackground(new java.awt.Color(255, 255, 255));
        btn_Profile.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn_Profile.setText("Profile");
        btn_Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProfileActionPerformed(evt);
            }
        });

        btn_Opleiding.setBackground(new java.awt.Color(255, 255, 255));
        btn_Opleiding.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn_Opleiding.setText("Opleidingen");
        btn_Opleiding.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Opleiding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OpleidingActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Opleiding, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btn_Profile)
                .addGap(18, 18, 18)
                .addComponent(btn_Opleiding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        getContentPane().add(sidePanel);
        sidePanel.setBounds(0, 0, 228, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProfileActionPerformed
        getUserData();
        Profile_Panel.setVisible(true);
        PanelOpleiding.setVisible(false);
    }//GEN-LAST:event_btn_ProfileActionPerformed

    private void btn_OpleidingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OpleidingActionPerformed
        // TODO add your handling code here:
        Profile_Panel.setVisible(false);
        PanelOpleiding.setVisible(true);
        btn_Survey.setVisible(false);
        btn_Verwwijder.setVisible(false);

        list_OpleidingLaden();
    }//GEN-LAST:event_btn_OpleidingActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        try {
            // TODO add your handling code here:
            wijzig_user();
        } catch (Exception ex) {
            Logger.getLogger(Home_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_AllOpleidingenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AllOpleidingenActionPerformed
        // TODO add your handling code here:

        Home_AllOpleidingen mf = new Home_AllOpleidingen();
        // set the jframe size and location, and make it visible
        mf.setPreferredSize(new Dimension(361, 450));
        mf.pack();
        mf.setTitle("Opleiding System");
        mf.setLocationRelativeTo(null);
        mf.setVisible(rootPaneCheckingEnabled);
        mf.list_OpleidingLaden();

        this.setVisible(false);

    }//GEN-LAST:event_btn_AllOpleidingenActionPerformed

    private void btn_VerwwijderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerwwijderActionPerformed
        try {
            // TODO add your handling code here:
            verwijder_opleiding_DB();
        } catch (Exception ex) {
            Logger.getLogger(Home_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_VerwwijderActionPerformed

    public void inLaden() {

        getUserData();
        Profile_Panel.setVisible(false);
        PanelOpleiding.setVisible(false);

    }

    public void home() {
        Profile_Panel.setVisible(false);
        PanelOpleiding.setVisible(false);
        sidePanel.setVisible(true);
    }

    public void opleidingSHow() {
        Profile_Panel.setVisible(false);
        PanelOpleiding.setVisible(true);
        sidePanel.setVisible(true);
        btn_Survey.setVisible(false);
        btn_Verwwijder.setVisible(false);
    }

    public void main() {

        MouseListener mouseListener = new MouseAdapter() {
            public void mouseClicked(MouseEvent mouseEvent) {
                JList<String> theList = (JList) mouseEvent.getSource();
                if (mouseEvent.getClickCount() == 1) {
                    int index = theList.locationToIndex(mouseEvent.getPoint());
                    if (index >= 0) {
                        Object o = theList.getModel().getElementAt(index);
                        String[] parts = o.toString().split("°");
                        String opleiding_Id = parts[1];
                        System.out.println(opleiding_Id);

                        btn_Survey.setVisible(true);
                        btn_Verwwijder.setVisible(true);

                    }
                }
            }
        };
        list_opleiding.addMouseListener(mouseListener);

    }

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_JFrame().setVisible(false);
            }
        });
    }

    private Connection connect = null;
    private Statement statement = null;
    private PreparedStatement preparedStatement = null;
    private ResultSet resultSet = null;

    public void wijzig_user() throws Exception {
        try {
            // This will load the MySQL driver, each DB has its own driver
            Class.forName("com.mysql.jdbc.Driver");
            // Setup the connection with the DB
            connect = DriverManager
                    .getConnection("jdbc:mysql://localhost/stagedb?"
                            + "user=root&password=");

            // PreparedStatements can use variables and are more efficient
            preparedStatement = connect
                    .prepareStatement("UPDATE `user` SET `name` = ?, `firstname` = ?, `gender`=?,`birthDate` = ?, `email` = ? WHERE `user`.`id` = ?");
            // "myuser, webpage, datum, summary, COMMENTS from feedback.comments");
            // Parameters start with 1
            preparedStatement.setString(1, txt_Name.getText());
            preparedStatement.setString(2, txt_firstname.getText());
            preparedStatement.setString(5, txt_email.getText());
            preparedStatement.setString(3, txt_gender.getText());
            preparedStatement.setString(4, txt_geboorteDatum.getText());

            var userId = Login.user_Data.getId();
            preparedStatement.setString(6, userId);

            preparedStatement.executeUpdate();
            JOptionPane.showMessageDialog(null, "user wijzigt");

        } catch (Exception e) {
            throw e;
        }

    }

    public void list_OpleidingLaden() {

        PreparedStatement ps;
        ResultSet rs;

        DefaultListModel model = new DefaultListModel();

        String query = "SELECT * FROM `opleiding` INNER JOIN `user_opleiding` ON `opleiding`.`id` = `user_opleiding`.`opleidingId` && user_opleiding.userId = ? ";

        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            var user_data = Login.user_Data;
            ps.setString(1, user_data.getId());
            rs = ps.executeQuery();

            while (rs.next()) {

                model.addElement(rs.getString("opleiding") + "                                                                                                                                                  °" + rs.getString("id") + "");

                // this.dispose();
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        jScrollPane1.setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_NEVER);
        list_opleiding.setModel(model);

    }

    public void getUserData() {
        // TODO add your handling code here:

        PreparedStatement ps;
        ResultSet rs;

        String query = "SELECT * FROM `user` WHERE id =  ?";

        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            var user_data = Login.user_Data;
            ps.setString(1, user_data.getId());
            rs = ps.executeQuery();

            while (rs.next()) {
                txt_Name.setText(rs.getString("name"));
                txt_firstname.setText(rs.getString("firstname"));
                txt_gender.setText(rs.getString("gender"));
                txt_geboorteDatum.setText(rs.getString("birthDate"));

                txt_user.setText(rs.getString("username"));
                txt_email.setText(rs.getString("email"));
                txt_role.setText(rs.getString("role"));
                // this.dispose();
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    public void verwijder_opleiding_DB() throws Exception {
        try {
            // This will load the MySQL driver, each DB has its own driver
            Class.forName("com.mysql.jdbc.Driver");
            // Setup the connection with the DB
            connect = DriverManager
                    .getConnection("jdbc:mysql://localhost/stagedb?"
                            + "user=root&password=");

            // PreparedStatements can use variables and are more efficient
            preparedStatement = connect
                    .prepareStatement("DELETE FROM `user_opleiding` WHERE `user_opleiding`.`userId` = ? && `user_opleiding`.`opleidingId` = ?");
            // "myuser, webpage, datum, summary, COMMENTS from feedback.comments");
            // Parameters start with 1
            int firstSelIx = list_opleiding.getSelectedIndex();
            Object sel = list_opleiding.getModel().getElementAt(firstSelIx);
            String string = sel.toString();
            String[] parts = string.split("°");
            String opleidingId = parts[1];

            var userId = Login.user_Data.getId();

            preparedStatement.setString(1, userId);
            preparedStatement.setString(2, opleidingId);

            preparedStatement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Opleiding verwijderd van u profile");

            list_OpleidingLaden();

        } catch (Exception e) {
            throw e;
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelOpleiding;
    private javax.swing.JPanel Profile_Panel;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btn_AllOpleidingen;
    private javax.swing.JButton btn_Opleiding;
    private javax.swing.JButton btn_Profile;
    private javax.swing.JButton btn_Survey;
    private javax.swing.JButton btn_Verwwijder;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_opleiding;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_geboorteDatum;
    private javax.swing.JTextField txt_gender;
    private javax.swing.JTextField txt_role;
    private javax.swing.JTextField txt_user;
    private javax.swing.JLabel txt_username;
    private javax.swing.JLabel txt_username1;
    private javax.swing.JLabel txt_username2;
    private javax.swing.JLabel txt_username3;
    private javax.swing.JLabel txt_username4;
    private javax.swing.JLabel txt_username5;
    private javax.swing.JLabel txt_username6;
    // End of variables declaration//GEN-END:variables
}
