/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanel.opleiding;

import javax.swing.BorderFactory;
import javax.swing.border.Border;
import jpanel.opleiding.Login;

/**
 *
 * @author singh
 */
public class Home_JFrame extends javax.swing.JFrame {

    private String[] info;

    public void setInfo(String[] info) {
        this.info = info;
    }

    /**
     * Creates new form Home_JFrame
     */
    public Home_JFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelOpleiding = new javax.swing.JPanel();
        ds = new javax.swing.JButton();
        Profile_Panel = new javax.swing.JPanel();
        txt_username = new javax.swing.JLabel();
        txt_username1 = new javax.swing.JLabel();
        txt_username2 = new javax.swing.JLabel();
        txt_username3 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_Name = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        txt_user = new javax.swing.JTextField();
        txt_role = new javax.swing.JTextField();
        txt_username4 = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        btn_Profile = new javax.swing.JButton();
        btn_Opleiding = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        PanelOpleiding.setLayout(null);

        ds.setText("Opleidingen");
        PanelOpleiding.add(ds);
        ds.setBounds(190, 210, 87, 21);

        getContentPane().add(PanelOpleiding);
        PanelOpleiding.setBounds(230, 0, 580, 460);

        Profile_Panel.setLayout(null);

        txt_username.setText("email");
        Profile_Panel.add(txt_username);
        txt_username.setBounds(70, 180, 40, 20);

        txt_username1.setText("Name");
        Profile_Panel.add(txt_username1);
        txt_username1.setBounds(70, 60, 60, 20);

        txt_username2.setText("Firstname");
        Profile_Panel.add(txt_username2);
        txt_username2.setBounds(70, 100, 140, 20);

        txt_username3.setText("Username");
        Profile_Panel.add(txt_username3);
        txt_username3.setBounds(70, 140, 60, 20);
        Profile_Panel.add(txt_email);
        txt_email.setBounds(140, 170, 230, 30);
        Profile_Panel.add(txt_Name);
        txt_Name.setBounds(140, 50, 230, 30);
        Profile_Panel.add(txt_firstname);
        txt_firstname.setBounds(140, 90, 230, 30);
        Profile_Panel.add(txt_user);
        txt_user.setBounds(140, 130, 230, 30);
        Profile_Panel.add(txt_role);
        txt_role.setBounds(140, 210, 230, 30);

        txt_username4.setText("role");
        Profile_Panel.add(txt_username4);
        txt_username4.setBounds(70, 210, 40, 20);

        getContentPane().add(Profile_Panel);
        Profile_Panel.setBounds(230, 0, 580, 460);

        sidePanel.setBackground(new java.awt.Color(0, 102, 204));

        btn_Profile.setBackground(new java.awt.Color(255, 255, 255));
        btn_Profile.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn_Profile.setText("Profile");
        btn_Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProfileActionPerformed(evt);
            }
        });

        btn_Opleiding.setBackground(new java.awt.Color(255, 255, 255));
        btn_Opleiding.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn_Opleiding.setText("Opleidingen");
        btn_Opleiding.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Opleiding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OpleidingActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Opleiding, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btn_Profile)
                .addGap(18, 18, 18)
                .addComponent(btn_Opleiding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(43, 43, 43))
        );

        getContentPane().add(sidePanel);
        sidePanel.setBounds(0, 0, 228, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProfileActionPerformed
        // TODO add your handling code here:
        Profile_Panel.setVisible(true);
        PanelOpleiding.setVisible(false);
    }//GEN-LAST:event_btn_ProfileActionPerformed

    private void btn_OpleidingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OpleidingActionPerformed
        // TODO add your handling code here:
        Profile_Panel.setVisible(false);
        PanelOpleiding.setVisible(true);
    }//GEN-LAST:event_btn_OpleidingActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    public void inLaden() {
        txt_user.setText(info[3]);
        txt_role.setText(info[0]);
        txt_Name.setText(info[1]);
        txt_firstname.setText(info[2]);
        txt_email.setText(info[4]);
        Profile_Panel.setVisible(false);
        PanelOpleiding.setVisible(false);

    }

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_JFrame().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelOpleiding;
    private javax.swing.JPanel Profile_Panel;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btn_Opleiding;
    private javax.swing.JButton btn_Profile;
    private javax.swing.JButton ds;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_role;
    private javax.swing.JTextField txt_user;
    private javax.swing.JLabel txt_username;
    private javax.swing.JLabel txt_username1;
    private javax.swing.JLabel txt_username2;
    private javax.swing.JLabel txt_username3;
    private javax.swing.JLabel txt_username4;
    // End of variables declaration//GEN-END:variables
}
