/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanel.opleiding.Admin;

import jpanel.opleiding.Auth.Login;
import jpanel.opleiding.Admin.OpleidingToevoegen;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;
import jpanel.opleiding.MyConnection;
import jpanel.opleiding.MyConnection;

/**
 *
 * @author singh
 */
public class Admin_page extends javax.swing.JFrame {

    private String[] info;
    private ArrayList<String> opleidingInfo;

    public void setInfo(String[] info) {
        this.info = info;
    }

    /**
     * Creates new form Admin_page
     */
    public Admin_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_opleiding = new javax.swing.JList<>();
        txt_opleiding = new javax.swing.JTextField();
        txt_locatie = new javax.swing.JTextField();
        txt_datum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_wijzigen = new javax.swing.JButton();
        txt_ID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_verwijderen = new javax.swing.JButton();
        btn_Toevoegen = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_surveyToevoegen = new javax.swing.JButton();
        btn_surveyTonen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(list_opleiding);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 10, 210, 250);
        getContentPane().add(txt_opleiding);
        txt_opleiding.setBounds(350, 80, 240, 40);

        txt_locatie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_locatieActionPerformed(evt);
            }
        });
        getContentPane().add(txt_locatie);
        txt_locatie.setBounds(350, 150, 240, 40);
        getContentPane().add(txt_datum);
        txt_datum.setBounds(350, 220, 240, 40);

        jLabel1.setText("Datum");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 200, 170, 13);

        jLabel2.setText("Opleiding");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 60, 70, 13);

        jLabel3.setText("Locatie");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 130, 110, 13);

        btn_wijzigen.setText("Wijzigen");
        btn_wijzigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_wijzigenActionPerformed(evt);
            }
        });
        getContentPane().add(btn_wijzigen);
        btn_wijzigen.setBounds(350, 280, 120, 21);
        getContentPane().add(txt_ID);
        txt_ID.setBounds(350, 30, 240, 20);

        jLabel4.setText("Id");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 10, 70, 13);

        jPanel1.setBackground(new java.awt.Color(0, 204, 203));
        jPanel1.setLayout(null);

        btn_verwijderen.setText("Verwijderen");
        btn_verwijderen.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btn_verwijderenAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btn_verwijderen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verwijderenActionPerformed(evt);
            }
        });
        jPanel1.add(btn_verwijderen);
        btn_verwijderen.setBounds(470, 280, 120, 21);

        btn_Toevoegen.setText("Opleiding Toevoegen");
        btn_Toevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ToevoegenActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Toevoegen);
        btn_Toevoegen.setBounds(20, 280, 210, 21);

        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout);
        btn_logout.setBounds(840, 280, 100, 21);

        btn_surveyToevoegen.setText("survey Tonen");
        jPanel1.add(btn_surveyToevoegen);
        btn_surveyToevoegen.setBounds(800, 60, 140, 20);

        btn_surveyTonen.setText("survey Toevoegen");
        jPanel1.add(btn_surveyTonen);
        btn_surveyTonen.setBounds(800, 30, 140, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 950, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_locatieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_locatieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_locatieActionPerformed

    private void btn_verwijderenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verwijderenActionPerformed
        try {
            // TODO add your handling code here:
            verwijder_database();
        } catch (Exception ex) {
            Logger.getLogger(Admin_page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_verwijderenActionPerformed

    private void btn_verwijderenAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btn_verwijderenAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_verwijderenAncestorAdded

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }// GEN-LAST:event_btn_logoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        PreparedStatement ps;
        ResultSet rs;

        DefaultListModel model = new DefaultListModel();

        String query = "SELECT * FROM `opleiding`";

        try {
            ps = MyConnection.getConnection().prepareStatement(query);

            rs = ps.executeQuery();

            while (rs.next()) {

                model.addElement(rs.getString("opleiding") + "                                                           °" + rs.getString("id") + "");

                // this.dispose();
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        list_opleiding.setModel(model);
    }// GEN-LAST:event_jButton1ActionPerformed

    private void btn_ToevoegenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_ToevoegenActionPerformed
        // TODO add your handling code here:

        OpleidingToevoegen opleidingtoevoegen = new OpleidingToevoegen();
        opleidingtoevoegen.setVisible(rootPaneCheckingEnabled);
        opleidingtoevoegen.setPreferredSize(new Dimension(346, 324));

        opleidingtoevoegen.pack();
        opleidingtoevoegen.setLocationRelativeTo(null);
        opleidingtoevoegen.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);

    }// GEN-LAST:event_btn_ToevoegenActionPerformed

    private void btn_wijzigenActionPerformed(java.awt.event.ActionEvent evt) {

        try {
            wijzig_database();
        } catch (Exception ex) {
            Logger.getLogger(Admin_page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_btn_wijzigenActionPerformed

    public static void main(String[] args) {
    }

    public void main() {

        MouseListener mouseListener = new MouseAdapter() {
            public void mouseClicked(MouseEvent mouseEvent) {
                JList<String> theList = (JList) mouseEvent.getSource();
                if (mouseEvent.getClickCount() == 2) {
                    int index = theList.locationToIndex(mouseEvent.getPoint());
                    if (index >= 0) {
                        Object o = theList.getModel().getElementAt(index);
                        String[] parts = o.toString().split("°");
                        String opleiding_Id = parts[1];

                        System.out.println(opleiding_Id);
                        showOpleidingInfo(opleiding_Id);

                    }
                }
            }
        };
        list_opleiding.addMouseListener(mouseListener);
        txt_opleiding.hide();
        txt_locatie.hide();
        txt_datum.hide();
        txt_ID.hide();

        jLabel1.hide();
        jLabel4.hide();

        jLabel2.hide();
        jLabel3.hide();
        btn_wijzigen.hide();
        btn_verwijderen.hide();
        btn_surveyToevoegen.hide();
        btn_surveyTonen.hide();

    }

    public void showOpleidingInfo(String opleidingId) {
        PreparedStatement ps;
        ResultSet rs;

        String query = "SELECT * FROM `opleiding` WHERE id =  ?";

        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, opleidingId);
            rs = ps.executeQuery();

            while (rs.next()) {
                txt_ID.setText(rs.getString("id"));
                txt_opleiding.setText(rs.getString("opleiding"));
                txt_datum.setText(rs.getString("datum"));
                txt_locatie.setText(rs.getString("location"));

                txt_opleiding.setVisible(true);
                txt_locatie.setVisible(true);
                txt_datum.setVisible(true);
                txt_ID.setVisible(true);

                jLabel1.setVisible(true);
                jLabel4.setVisible(true);

                jLabel2.setVisible(true);
                jLabel3.setVisible(true);
                btn_wijzigen.setVisible(true);
                btn_verwijderen.setVisible(true);
                btn_surveyToevoegen.setVisible(true);
                btn_surveyTonen.setVisible(true);

                // this.dispose();
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public void listInladen() {

        PreparedStatement ps;
        ResultSet rs;

        DefaultListModel model = new DefaultListModel();

        String query = "SELECT * FROM `opleiding`";

        try {
            ps = MyConnection.getConnection().prepareStatement(query);

            rs = ps.executeQuery();

            while (rs.next()) {

                model.addElement(rs.getString("opleiding") + "                                                                          °" + rs.getString("id") + "");

                // this.dispose();
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        jScrollPane1.setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_NEVER);

        list_opleiding.setModel(model);

    }

    private Connection connect = null;
    private Statement statement = null;
    private PreparedStatement preparedStatement = null;
    private ResultSet resultSet = null;

    public void wijzig_database() throws Exception {
        try {
            // This will load the MySQL driver, each DB has its own driver
            Class.forName("com.mysql.jdbc.Driver");
            // Setup the connection with the DB
            connect = DriverManager
                    .getConnection("jdbc:mysql://localhost/stagedb?"
                            + "user=root&password=");

            // PreparedStatements can use variables and are more efficient
            preparedStatement = connect
                    .prepareStatement("UPDATE `opleiding` SET `opleiding` = ?, `location` = ?, `datum` = ? WHERE `opleiding`.`id` = ?");
            // "myuser, webpage, datum, summary, COMMENTS from feedback.comments");
            // Parameters start with 1
            preparedStatement.setString(1, txt_opleiding.getText());
            preparedStatement.setString(2, txt_locatie.getText());

            preparedStatement.setString(4, txt_ID.getText());

            String sDate1 = txt_datum.getText();

            preparedStatement.setDate(3, java.sql.Date.valueOf(sDate1));

            preparedStatement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Opleiding wijzigt");
            listInladen();

        } catch (Exception e) {
            throw e;
        }

    }

    public void verwijder_database() throws Exception {
        try {
            // This will load the MySQL driver, each DB has its own driver
            Class.forName("com.mysql.jdbc.Driver");
            // Setup the connection with the DB
            connect = DriverManager
                    .getConnection("jdbc:mysql://localhost/stagedb?"
                            + "user=root&password=");

            // PreparedStatements can use variables and are more efficient
            preparedStatement = connect
                    .prepareStatement("DELETE FROM `opleiding` WHERE `opleiding`.`id` = ?");
            // "myuser, webpage, datum, summary, COMMENTS from feedback.comments");
            // Parameters start with 1
            preparedStatement.setString(1, txt_ID.getText());

            preparedStatement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Opleiding verwijderd");
            txt_ID.setText("");
            txt_opleiding.setText("");
            txt_datum.setText("");
            txt_locatie.setText("");
            txt_opleiding.hide();
            txt_locatie.hide();
            txt_datum.hide();
            txt_ID.hide();

            jLabel1.hide();
            jLabel4.hide();

            jLabel2.hide();
            jLabel3.hide();
            btn_wijzigen.hide();
            btn_verwijderen.hide();
            btn_surveyToevoegen.hide();
            btn_surveyTonen.hide();

            listInladen();

        } catch (Exception e) {
            throw e;
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Toevoegen;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_surveyToevoegen;
    private javax.swing.JButton btn_surveyTonen;
    private javax.swing.JButton btn_verwijderen;
    private javax.swing.JButton btn_wijzigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_opleiding;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_datum;
    private javax.swing.JTextField txt_locatie;
    private javax.swing.JTextField txt_opleiding;
    // End of variables declaration//GEN-END:variables
}
