/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanel.opleiding.Home;

import javax.swing.DefaultListModel;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;
import jpanel.opleiding.Auth.Login;
import jpanel.opleiding.MyConnection;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author singh
 */
public class Home_AllOpleidingen extends javax.swing.JFrame {

    /**
     * Creates new form Home_AllOpleidingen
     */
    public Home_AllOpleidingen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_opleiding = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_DeelNemen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(list_opleiding);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 30, 300, 330);

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 31, 29);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("All Opleidingen");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 300, 13);

        btn_DeelNemen.setText("Deel nemen");
        btn_DeelNemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeelNemenActionPerformed(evt);
            }
        });
        getContentPane().add(btn_DeelNemen);
        btn_DeelNemen.setBounds(90, 370, 180, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Home_JFrame mf = new Home_JFrame();
        // set the jframe size and location, and make it visible
        mf.setPreferredSize(new Dimension(800, 500));
        mf.pack();
        mf.setTitle("Opleiding System");
        mf.setLocationRelativeTo(null);
        mf.setVisible(rootPaneCheckingEnabled);
        mf.opleidingSHow();
        mf.main();
        mf.list_OpleidingLaden();
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private Connection connect = null;
    private Statement statement = null;
    private PreparedStatement preparedStatement = null;
    private ResultSet resultSet = null;

    public void AddOpleiding_DB(String userId, String opleidingId) throws Exception {
        try {
            // This will load the MySQL driver, each DB has its own driver
            Class.forName("com.mysql.jdbc.Driver");
            // Setup the connection with the DB
            connect = MyConnection.getConnection();

            // PreparedStatements can use variables and are more efficient
            preparedStatement = connect
                    .prepareStatement("INSERT INTO `user_opleiding` (`id`, `userId`, `opleidingId`) VALUES (NULL, ?, ?)");
            // "myuser, webpage, datum, summary, COMMENTS from feedback.comments");
            // Parameters start with 1
            preparedStatement.setString(1, userId);
            preparedStatement.setString(2, opleidingId);

            preparedStatement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Opleiding Toegevoegd aan u profile");
            Home_JFrame mf = new Home_JFrame();
            // set the jframe size and location, and make it visible
            mf.setPreferredSize(new Dimension(800, 500));
            mf.pack();
            mf.setTitle("Opleiding System");
            mf.setLocationRelativeTo(null);
            mf.setVisible(rootPaneCheckingEnabled);
            mf.opleidingSHow();
            mf.main();
            mf.list_OpleidingLaden();
            this.setVisible(false);

        } catch (Exception e) {
            throw e;
        }

    }
    private void btn_DeelNemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeelNemenActionPerformed
        // TODO add your handling code here:
        int firstSelIx = list_opleiding.getSelectedIndex();
        Object sel = list_opleiding.getModel().getElementAt(firstSelIx);
        String string = sel.toString();
        String[] parts = string.split("°");
        String id = parts[1];

        var userId = Login.user_Data.getId();
        var opleidingId = id;

        try {
            AddOpleiding_DB(userId, opleidingId);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Home_AllOpleidingen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_DeelNemenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_AllOpleidingen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_AllOpleidingen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_AllOpleidingen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_AllOpleidingen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_AllOpleidingen().setVisible(true);
            }
        });
    }

    public void list_OpleidingLaden() {

        PreparedStatement ps;
        ResultSet rs;

        DefaultListModel model = new DefaultListModel();

        String query = "SELECT * FROM `opleiding`";

        try {
            ps = MyConnection.getConnection().prepareStatement(query);

            rs = ps.executeQuery();

            while (rs.next()) {

                model.addElement(rs.getString("opleiding") + "                                                                                                                                                                                           °" + rs.getString("id") + "");

                // this.dispose();
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        jScrollPane1.setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_NEVER);
        list_opleiding.setModel(model);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DeelNemen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_opleiding;
    // End of variables declaration//GEN-END:variables
}
